# additions to .bash_profile for setting up git
# add to .bash_profile so as not to interfere with FTP transfers

# start ssh-agent for git and add non-standard key
eval "$(ssh-agent -s)"
ssh-add /p/home/$USER/.ssh/id_rsa_git

# add entire git repo to PATH
for dir in /p/home/$USER/.local_programs/asepylot/*; do PATH="$PATH:$dir"; done
