# additions to .bash_profile for setting up git
# add to .bash_profile so as not to interfere with FTP transfers

# start ssh-agent for git and add non-standard key
eval "$(ssh-agent -s)"
ssh-add /p/home/$USER/.ssh/id_rsa_git

# add entire git repo to PATH
for dir in /p/home/$USER/.local_programs/asepylot/*; do PATH="$PATH:$dir"; done

# add functions library to Python path
export PYTHONPATH=$PYTHONPATH:/p/home/$USER/.local_programs/asepylot/pylot_lite

# command to update asepylot on all machines
update_asepylot () {
 ping=`pwd`
 if [ -d $HOME/.local_programs/asepylot ]; then
  cd $HOME/.local_programs/asepylot
  git pull
 else
  git clone https://github.com/pollardtp/asepylot.git $HOME/.local_programs/asepylot
 fi
 cd $ping
}
