#!/bin/bash

mkdir -p ~/.local_programs
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh <<%EOF%

yes
/p/home/$USER/.local_programs/conda3
yes
%EOF%

source ~/.bashrc
bash initase_
bash initgit_

cp ~/.bashrc ~/.bashrc.bak

cat > fkjshdkfhwldf.txt <<%EOF%

# start ssh-agent for git and add non-standard key
eval "$(ssh-agent -s)"
ssh-add /p/home/$USER/.ssh/id_rsa_git
%EOF%

cat ~/.bashrc fkjshdkfhwldf.txt > ~/.bashrc
rm fkjshdkfhwldf.txt
source ~/.bashrc

echo "Now run... (passphrase not necessary, just hit RETURN twice)"
echo "ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa_git -C 'pollartpuc@gmail.com'"
echo "Clip contents of ~/.ssh/id_rsa_git.pub [IMPORTANT: grab PUBLIC key ONLY, .pub]"
echo "Add to github in Settings."

